cleanlab/cleanlab-tlm

- src/cleanlab_tlm/tlm.py
cc @huiwengoh @jas2600 
Please help us keep recommendations up-to-date when adding new models.
> update recommended models

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/internal/constants.py
- src/cleanlab_tlm/tlm.py
- tests/constants.py
note: do not merge until backend is deployed
> Add support for gpt-4.5-preview 

- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/utils/rag.py
> Fix RAG module docs

- src/cleanlab_tlm/errors.py
- src/cleanlab_tlm/internal/api/api.py
- src/cleanlab_tlm/internal/exception_handling.py
Closes https://github.com/cleanlab/cleanlab-tlm/issues/7
> Better error messaging for incorrect API key

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
> release new context_sufficiency criteria

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/utils/rag.py
> TrustworthyRAG set retries

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/errors.py
- src/cleanlab_tlm/internal/api/api.py
longer term: 1) implement try methods in the client lib 2) dedicated error code for this random invalid json parsing from server and handle separately from client
- Priority: 
---
- Tested...
> short term mitigation for random invalid json parsing

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/tlm.py
- src/cleanlab_tlm/utils/rag.py
> add batch processing message

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/utils/rag.py
[Link](https://www.notion.so/cleanlab/Benchmark-results-1dfc7fee85be807cafadeed980df402e) to benchmark results.
> Update query ease

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/internal/base.py
Should be merged after server side change is deployed
- Priority: 
---
- Tested...
> server side max_timeout

- src/cleanlab_tlm/utils/chat.py
- tests/test_chat.py
Moved `form_prompt_string` from `tlm_conversation` use-case tutorial here so it can be reused in other code.
> added chat.py

- CHANGELOG.md
- README.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/internal/api/api.py
- src/cleanlab_tlm/internal/constants.py
- src/cleanlab_tlm/tlm.py
- tests/constants.py
- tests/test_validation.py
[do not merge until backend changes are deployed]
> Update default model to gpt-4.1-mini

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
> release utils.chat

- src/cleanlab_tlm/utils/chat.py
- tests/test_chat.py
Design Overview:
If `instructions` are provided, this is prepended as a `System:` at the very beginning of the output string (before tool list as well).
If `developer` roles are present in the list of messages, these will use the `System:` prefix as well.
From [OpenAI API model spec](https://model-spec.openai.com/2025-02-12.html#chain_of_command):
> Here is the ordering of authority levels. Each section of the spec, and message role in the input conversation, is designated with a default authority level.
> 
> Platform: Model Spec "platform" sections and system messages
> Developer: Model Spec "developer" sections and developer messages
> User: Model Spec "user" sections and user messages
> Guideline: Model Spec "guideline" sections
> No Authority: assistant and tool messages; …
> Update chat.py to handle responses API `instructions` parameter

- pyproject.toml
- src/cleanlab_tlm/utils/chat.py
> chat completions type checking

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/utils/chat.py
- src/cleanlab_tlm/utils/chat_completions.py
- tests/test_chat.py
just getting something started
> better form response str

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/utils/chat.py
- src/cleanlab_tlm/utils/chat_completions.py
- src/cleanlab_tlm/utils/responses.py
> Add TLMResponses API

- pyproject.toml
- Implementation plan: link
- Priority: 
---
- Tested...
> [temp] pin openai version for CI

- tests/test_properties.py
Fix some unittests logic after the quality preset changes in https://github.com/cleanlab/cleanlab-tlm/pull/92
> Fix unittests

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/utils/vpc/chat_completions.py
- Implementation plan: link
- Priority: 
---
- Tested...
> [VPC ChatCompletions] Add explanations

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/internal/validation.py
- src/cleanlab_tlm/tlm.py
- tests/test_validation.py
- Implementation plan: link
- Priority: 
---
- Tested...
> add disable_persistence option to TLMOptions for codex requests in customer environments

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/tlm.py
- src/cleanlab_tlm/utils/rag.py
This will allow async TLM clients to call get explanations
> add public async methods for Get Explanations API

- CHANGELOG.md
- src/cleanlab_tlm/__about__.py
- src/cleanlab_tlm/internal/constants.py
- src/cleanlab_tlm/utils/chat_completions.py
- src/cleanlab_tlm/utils/per_field_score_utils.py
- src/cleanlab_tlm/utils/vpc/chat_completions.py
Similar to https://github.com/cleanlab/cleanlab-tlm/pull/120 but for VPC module
> [VPC ChatCompletion] Add functionality for structured outputs per-field scoring
